mod_loader=paper

included_projects=:common

paper_version=1.21.4-R0.1-SNAPSHOT

luckperms_version=5.5.17

modrinth_upload_supported_loaders=bukkit, spigot, paper, purpur, folia
modrinth_upload_required_dependencies=simple-voice-chat

enable_hangar_upload=true
hangar_upload_supported_loaders=PAPER
hangar_upload_minecraft_versions=1.21.4